# Generated by Django 5.1.3 on 2025-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
